Algoritmo "primo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ricardo Petri
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Luca Erichsen Cardoso, Pedro Henrique Ferri, Bruno Broietti Serenato
// Data atual  : 30/05/2022
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo